export const exercisesData = [
  // PEITO
  { nome: "Supino Reto com Barra", grupoMuscular: "Peito", equipamento: "Barra", dificuldade: "Intermediário", videoUrl: "https://www.youtube.com/watch?v=rT7DgCr-3pg" },
  { nome: "Supino Inclinado com Barra", grupoMuscular: "Peito", equipamento: "Barra", dificuldade: "Intermediário", videoUrl: "https://www.youtube.com/watch?v=jb5LQYJPVjo" },
  { nome: "Supino Declinado com Barra", grupoMuscular: "Peito", equipamento: "Barra", dificuldade: "Intermediário", videoUrl: "https://www.youtube.com/watch?v=LfyQBUKR8SE" },
  { nome: "Supino com Halteres", grupoMuscular: "Peito", equipamento: "Halteres", dificuldade: "Iniciante", videoUrl: "https://www.youtube.com/watch?v=VmB1G1K7v94" },
  { nome: "Supino Inclinado com Halteres", grupoMuscular: "Peito", equipamento: "Halteres", dificuldade: "Iniciante", videoUrl: "https://www.youtube.com/watch?v=8iPEnn-ltC8" },
  { nome: "Crucifixo com Halteres", grupoMuscular: "Peito", equipamento: "Halteres", dificuldade: "Iniciante", videoUrl: "https://www.youtube.com/watch?v=eozdVDA78K0" },
  { nome: "Crucifixo Inclinado", grupoMuscular: "Peito", equipamento: "Halteres", dificuldade: "Iniciante", videoUrl: "https://www.youtube.com/watch?v=sAq_ocpRh_I" },
  { nome: "Crossover", grupoMuscular: "Peito", equipamento: "Cabo", dificuldade: "Intermediário", videoUrl: "https://www.youtube.com/watch?v=taI4XduLpTk" },
  { nome: "Peck Deck (Voador)", grupoMuscular: "Peito", equipamento: "Máquina", dificuldade: "Iniciante", videoUrl: "https://www.youtube.com/watch?v=Z71bFZrVCVo" },
  { nome: "Flexão de Braço", grupoMuscular: "Peito", equipamento: "Peso Corporal", dificuldade: "Iniciante", videoUrl: "https://www.youtube.com/watch?v=IODxDxX7oi4" },
  { nome: "Flexão Declinada", grupoMuscular: "Peito", equipamento: "Peso Corporal", dificuldade: "Intermediário", videoUrl: "https://www.youtube.com/watch?v=Yb1H_GN5Cw4" },
  { nome: "Flexão com Pausa", grupoMuscular: "Peito", equipamento: "Peso Corporal", dificuldade: "Avançado", videoUrl: "https://www.youtube.com/watch?v=lffNjjXCOhM" },
  { nome: "Mergulho (Dips) no Banco", grupoMuscular: "Peito", equipamento: "Peso Corporal", dificuldade: "Iniciante", videoUrl: "https://www.youtube.com/watch?v=0326dy_-CzM" },
  { nome: "Supino na Máquina", grupoMuscular: "Peito", equipamento: "Máquina", dificuldade: "Iniciante", videoUrl: "https://www.youtube.com/watch?v=xUm0BiZCWlQ" },
  { nome: "Pullover com Halter", grupoMuscular: "Peito", equipamento: "Halteres", dificuldade: "Intermediário", videoUrl: "https://www.youtube.com/watch?v=sGl1IYdCT5w" },

  // COSTAS
  { nome: "Barra Fixa (Pull-up)", grupoMuscular: "Costas", equipamento: "Peso Corporal", dificuldade: "Avançado", videoUrl: "https://www.youtube.com/watch?v=eGo4IYlbE5g" },
  { nome: "Barra Fixa Supinada (Chin-up)", grupoMuscular: "Costas", equipamento: "Peso Corporal", dificuldade: "Intermediário", videoUrl: "https://www.youtube.com/watch?v=brhRXlOhkAA" },
  { nome: "Puxada Alta", grupoMuscular: "Costas", equipamento: "Máquina", dificuldade: "Iniciante", videoUrl: "https://www.youtube.com/watch?v=CAwf7n6Luuc" },
  { nome: "Puxada Alta Supinada", grupoMuscular: "Costas", equipamento: "Máquina", dificuldade: "Iniciante", videoUrl: "https://www.youtube.com/watch?v=rT1nGjGM2p8" },
  { nome: "Remada Curvada com Barra", grupoMuscular: "Costas", equipamento: "Barra", dificuldade: "Intermediário", videoUrl: "https://www.youtube.com/watch?v=kBWAon7ItDw" },
  { nome: "Remada Curvada Supinada", grupoMuscular: "Costas", equipamento: "Barra", dificuldade: "Intermediário", videoUrl: "https://www.youtube.com/watch?v=Auu7S3HQbJs" },
  { nome: "Remada Unilateral com Halter", grupoMuscular: "Costas", equipamento: "Halteres", dificuldade: "Iniciante", videoUrl: "https://www.youtube.com/watch?v=roCP6wCXPqo" },
  { nome: "Remada Cavalinho", grupoMuscular: "Costas", equipamento: "Barra", dificuldade: "Intermediário", videoUrl: "https://www.youtube.com/watch?v=j3Igk5nyZE4" },
  { nome: "Remada Baixa", grupoMuscular: "Costas", equipamento: "Máquina", dificuldade: "Iniciante", videoUrl: "https://www.youtube.com/watch?v=GZbfZ033f74" },
  { nome: "Remada Alta com Corda", grupoMuscular: "Costas", equipamento: "Cabo", dificuldade: "Iniciante", videoUrl: "https://www.youtube.com/watch?v=qZ_kY8MQy7E" },
  { nome: "Levantamento Terra (Deadlift)", grupoMuscular: "Costas", equipamento: "Barra", dificuldade: "Avançado", videoUrl: "https://www.youtube.com/watch?v=ytGaGIn3SjE" },
  { nome: "Levantamento Terra Sumô", grupoMuscular: "Costas", equipamento: "Barra", dificuldade: "Avançado", videoUrl: "https://www.youtube.com/watch?v=iw40ly3Y8Q0" },
  { nome: "Pulldown com Corda", grupoMuscular: "Costas", equipamento: "Cabo", dificuldade: "Intermediário", videoUrl: "https://www.youtube.com/watch?v=2w6vH2KnEkc" },
  { nome: "Remada Sentado na Máquina", grupoMuscular: "Costas", equipamento: "Máquina", dificuldade: "Iniciante", videoUrl: "https://www.youtube.com/watch?v=7XxWAJySz0Y" },
  { nome: "Pullover no Cabo", grupoMuscular: "Costas", equipamento: "Cabo", dificuldade: "Intermediário", videoUrl: "https://www.youtube.com/watch?v=KwdlXmNhVZ0" },
  { nome: "Hiperextensão Lombar", grupoMuscular: "Costas", equipamento: "Peso Corporal", dificuldade: "Iniciante", videoUrl: "https://www.youtube.com/watch?v=J1hMoI4I5X8" },
  { nome: "Good Morning", grupoMuscular: "Costas", equipamento: "Barra", dificuldade: "Intermediário", videoUrl: "https://www.youtube.com/watch?v=YA-h3n29T3w" },
  { nome: "Shrugs com Barra", grupoMuscular: "Costas", equipamento: "Barra", dificuldade: "Iniciante", videoUrl: "https://www.youtube.com/watch?v=cJRVVxmytaM" },

  // OMBROS
  { nome: "Desenvolvimento com Barra", grupoMuscular: "Ombros", equipamento: "Barra", dificuldade: "Intermediário", videoUrl: "https://www.youtube.com/watch?v=QAQ64hK4Xxs" },
  { nome: "Desenvolvimento com Halteres", grupoMuscular: "Ombros", equipamento: "Halteres", dificuldade: "Iniciante", videoUrl: "https://www.youtube.com/watch?v=qEwKCR5JCog" },
  { nome: "Desenvolvimento Arnold", grupoMuscular: "Ombros", equipamento: "Halteres", dificuldade: "Intermediário", videoUrl: "https://www.youtube.com/watch?v=6Z15_WdXmVw" },
  { nome: "Elevação Lateral", grupoMuscular: "Ombros", equipamento: "Halteres", dificuldade: "Iniciante", videoUrl: "https://www.youtube.com/watch?v=3VcKaXpzqRo" },
  { nome: "Elevação Lateral Inclinado", grupoMuscular: "Ombros", equipamento: "Halteres", dificuldade: "Intermediário", videoUrl: "https://www.youtube.com/watch?v=WqZxT0uzAHs" },
  { nome: "Elevação Frontal", grupoMuscular: "Ombros", equipamento: "Halteres", dificuldade: "Iniciante", videoUrl: "https://www.youtube.com/watch?v=qkx-rpgh27w" },
  { nome: "Crucifixo Inverso", grupoMuscular: "Ombros", equipamento: "Halteres", dificuldade: "Intermediário", videoUrl: "https://www.youtube.com/watch?v=tTKY4kcP9ZI" },
  { nome: "Remada Alta", grupoMuscular: "Ombros", equipamento: "Barra", dificuldade: "Intermediário", videoUrl: "https://www.youtube.com/watch?v=qkrUv-7s8Ik" },
  { nome: "Face Pull", grupoMuscular: "Ombros", equipamento: "Cabo", dificuldade: "Intermediário", videoUrl: "https://www.youtube.com/watch?v=rep-qVOkqgk" },
  { nome: "Elevação Lateral no Cabo", grupoMuscular: "Ombros", equipamento: "Cabo", dificuldade: "Intermediário", videoUrl: "https://www.youtube.com/watch?v=3bJHvKshZP8" },
  { nome: "Desenvolvimento na Máquina", grupoMuscular: "Ombros", equipamento: "Máquina", dificuldade: "Iniciante", videoUrl: "https://www.youtube.com/watch?v=FnPgXKBUy0k" },
  { nome: "Crucifixo Inverso na Máquina", grupoMuscular: "Ombros", equipamento: "Máquina", dificuldade: "Iniciante", videoUrl: "https://www.youtube.com/watch?v=_JJQi_MYW_E" },

  // PERNAS - QUADRÍCEPS
  { nome: "Agachamento Livre", grupoMuscular: "Pernas - Quadríceps", equipamento: "Barra", dificuldade: "Avançado", videoUrl: "https://www.youtube.com/watch?v=ultWZbUMPL8" },
  { nome: "Agachamento Frontal", grupoMuscular: "Pernas - Quadríceps", equipamento: "Barra", dificuldade: "Avançado", videoUrl: "https://www.youtube.com/watch?v=NkMHIH_LTiE" },
  { nome: "Agachamento Sumô", grupoMuscular: "Pernas - Quadríceps", equipamento: "Halteres", dificuldade: "Intermediário", videoUrl: "https://www.youtube.com/watch?v=0ry_-l0JuPc" },
  { nome: "Agachamento no Hack", grupoMuscular: "Pernas - Quadríceps", equipamento: "Máquina", dificuldade: "Intermediário", videoUrl: "https://www.youtube.com/watch?v=EdtaJRBqwes" },
  { nome: "Leg Press 45°", grupoMuscular: "Pernas - Quadríceps", equipamento: "Máquina", dificuldade: "Iniciante", videoUrl: "https://www.youtube.com/watch?v=yQXnOuQqKYc" },
  { nome: "Leg Press Horizontal", grupoMuscular: "Pernas - Quadríceps", equipamento: "Máquina", dificuldade: "Iniciante", videoUrl: "https://www.youtube.com/watch?v=o0RMHlPaLlg" },
  { nome: "Cadeira Extensora", grupoMuscular: "Pernas - Quadríceps", equipamento: "Máquina", dificuldade: "Iniciante", videoUrl: "https://www.youtube.com/watch?v=YyvSfVjQeL0" },
  { nome: "Afundo (Lunge)", grupoMuscular: "Pernas - Quadríceps", equipamento: "Halteres", dificuldade: "Intermediário", videoUrl: "https://www.youtube.com/watch?v=QOVaHwm-Q6U" },
  { nome: "Afundo Búlgaro", grupoMuscular: "Pernas - Quadríceps", equipamento: "Halteres", dificuldade: "Intermediário", videoUrl: "https://www.youtube.com/watch?v=2C-uNgKwPLE" },
  { nome: "Sissy Squat", grupoMuscular: "Pernas - Quadríceps", equipamento: "Peso Corporal", dificuldade: "Avançado", videoUrl: "https://www.youtube.com/watch?v=r0zr6kfhEJk" },
  { nome: "Agachamento Goblet", grupoMuscular: "Pernas - Quadríceps", equipamento: "Halteres", dificuldade: "Iniciante", videoUrl: "https://www.youtube.com/watch?v=MeHQ4A4wO7A" },
  { nome: "Step Up", grupoMuscular: "Pernas - Quadríceps", equipamento: "Halteres", dificuldade: "Intermediário", videoUrl: "https://www.youtube.com/watch?v=dVHdrd03-nc" },

  // PERNAS - POSTERIORES
  { nome: "Levantamento Terra Romeno", grupoMuscular: "Pernas - Posteriores", equipamento: "Barra", dificuldade: "Intermediário", videoUrl: "https://www.youtube.com/watch?v=2SHsk9AzdjA" },
  { nome: "Stiff com Barra", grupoMuscular: "Pernas - Posteriores", equipamento: "Barra", dificuldade: "Intermediário", videoUrl: "https://www.youtube.com/watch?v=1uDiW5--rAE" },
  { nome: "Stiff com Halteres", grupoMuscular: "Pernas - Posteriores", equipamento: "Halteres", dificuldade: "Intermediário", videoUrl: "https://www.youtube.com/watch?v=9hNmjGZYy8s" },
  { nome: "Mesa Flexora", grupoMuscular: "Pernas - Posteriores", equipamento: "Máquina", dificuldade: "Iniciante", videoUrl: "https://www.youtube.com/watch?v=yzvPiEqCi_U" },
  { nome: "Cadeira Flexora", grupoMuscular: "Pernas - Posteriores", equipamento: "Máquina", dificuldade: "Iniciante", videoUrl: "https://www.youtube.com/watch?v=QkvGC4MnOfM" },
  { nome: "Glute Ham Raise", grupoMuscular: "Pernas - Posteriores", equipamento: "Peso Corporal", dificuldade: "Avançado", videoUrl: "https://www.youtube.com/watch?v=VQqp5LAfBFs" },
  { nome: "Hip Thrust com Barra", grupoMuscular: "Pernas - Posteriores", equipamento: "Barra", dificuldade: "Intermediário", videoUrl: "https://www.youtube.com/watch?v=xDmFkJxPzeM" },
  { nome: "Abdução de Quadril na Máquina", grupoMuscular: "Pernas - Posteriores", equipamento: "Máquina", dificuldade: "Iniciante", videoUrl: "https://www.youtube.com/watch?v=3lboWqDZj2o" },
  { nome: "Coice no Cabo", grupoMuscular: "Pernas - Posteriores", equipamento: "Cabo", dificuldade: "Intermediário", videoUrl: "https://www.youtube.com/watch?v=b-8Fzyf-7Xg" },
  { nome: "Ponte (Hip Bridge)", grupoMuscular: "Pernas - Posteriores", equipamento: "Peso Corporal", dificuldade: "Iniciante", videoUrl: "https://www.youtube.com/watch?v=0Vz5MUfUizg" },

  // BÍCEPS
  { nome: "Rosca Direta com Barra", grupoMuscular: "Braços - Bíceps", equipamento: "Barra", dificuldade: "Iniciante", videoUrl: "https://www.youtube.com/watch?v=kwG2ipFRgfo" },
  { nome: "Rosca Direta com Barra W", grupoMuscular: "Braços - Bíceps", equipamento: "Barra", dificuldade: "Iniciante", videoUrl: "https://www.youtube.com/watch?v=soxrZlIl35U" },
  { nome: "Rosca Alternada com Halteres", grupoMuscular: "Braços - Bíceps", equipamento: "Halteres", dificuldade: "Iniciante", videoUrl: "https://www.youtube.com/watch?v=G6feTR1uIG4" },
  { nome: "Rosca Simultânea com Halteres", grupoMuscular: "Braços - Bíceps", equipamento: "Halteres", dificuldade: "Iniciante", videoUrl: "https://www.youtube.com/watch?v=R_QeD5w8Vw8" },
  { nome: "Rosca Martelo", grupoMuscular: "Braços - Bíceps", equipamento: "Halteres", dificuldade: "Iniciante", videoUrl: "https://www.youtube.com/watch?v=zC3nLlEvin4" },
  { nome: "Rosca Concentrada", grupoMuscular: "Braços - Bíceps", equipamento: "Halteres", dificuldade: "Intermediário", videoUrl: "https://www.youtube.com/watch?v=0AUGkch3tzc" },
  { nome: "Rosca Scott com Barra", grupoMuscular: "Braços - Bíceps", equipamento: "Máquina/Barra", dificuldade: "Iniciante", videoUrl: "https://www.youtube.com/watch?v=5H7VS8TdZVs" },
  { nome: "Rosca Scott com Halteres", grupoMuscular: "Braços - Bíceps", equipamento: "Máquina/Halteres", dificuldade: "Iniciante", videoUrl: "https://www.youtube.com/watch?v=qNTdN97eYWE" },
  { nome: "Rosca no Cabo", grupoMuscular: "Braços - Bíceps", equipamento: "Cabo", dificuldade: "Iniciante", videoUrl: "https://www.youtube.com/watch?v=8p6W7Zwcqzs" },
  { nome: "Rosca Inversa", grupoMuscular: "Braços - Bíceps", equipamento: "Barra", dificuldade: "Intermediário", videoUrl: "https://www.youtube.com/watch?v=nRgxYX2Ve9w" },

  // TRÍCEPS
  { nome: "Supino Fechado", grupoMuscular: "Braços - Tríceps", equipamento: "Barra", dificuldade: "Intermediário", videoUrl: "https://www.youtube.com/watch?v=nEF0bv2FW94" },
  { nome: "Tríceps Testa (Skull Crusher)", grupoMuscular: "Braços - Tríceps", equipamento: "Barra", dificuldade: "Intermediário", videoUrl: "https://www.youtube.com/watch?v=d_KZxkY_0cM" },
  { nome: "Tríceps Francês com Halteres", grupoMuscular: "Braços - Tríceps", equipamento: "Halteres", dificuldade: "Intermediário", videoUrl: "https://www.youtube.com/watch?v=YbX7Wd8jQ-Q" },
  { nome: "Tríceps Corda", grupoMuscular: "Braços - Tríceps", equipamento: "Cabo", dificuldade: "Iniciante", videoUrl: "https://www.youtube.com/watch?v=2-LAMcpzODU" },
  { nome: "Tríceps Barra", grupoMuscular: "Braços - Tríceps", equipamento: "Cabo", dificuldade: "Iniciante", videoUrl: "https://www.youtube.com/watch?v=_gsUck-7M74" },
  { nome: "Mergulho (Dips) nas Paralelas", grupoMuscular: "Braços - Tríceps", equipamento: "Peso Corporal", dificuldade: "Intermediário", videoUrl: "https://www.youtube.com/watch?v=2z8JmcrW-As" },
  { nome: "Coice com Halter", grupoMuscular: "Braços - Tríceps", equipamento: "Halteres", dificuldade: "Iniciante", videoUrl: "https://www.youtube.com/watch?v=_qJ2Urbh_34" },
  { nome: "Tríceps Unilateral no Cabo", grupoMuscular: "Braços - Tríceps", equipamento: "Cabo", dificuldade: "Iniciante", videoUrl: "https://www.youtube.com/watch?v=lKB9aVWyDxg" },
  { nome: "Tríceps Supinado", grupoMuscular: "Braços - Tríceps", equipamento: "Barra", dificuldade: "Intermediário", videoUrl: "https://www.youtube.com/watch?v=y7-2YxW7dL0" },
  { nome: "Extensão de Tríceps na Máquina", grupoMuscular: "Braços - Tríceps", equipamento: "Máquina", dificuldade: "Iniciante", videoUrl: "https://www.youtube.com/watch?v=IDZZT0e2UHk" },

  // CORE/ABDÔMEN
  { nome: "Prancha (Plank)", grupoMuscular: "Core/Abdômen", equipamento: "Peso Corporal", dificuldade: "Iniciante", videoUrl: "https://www.youtube.com/watch?v=pSHjTRCQxIw" },
  { nome: "Prancha Lateral", grupoMuscular: "Core/Abdômen", equipamento: "Peso Corporal", dificuldade: "Intermediário", videoUrl: "https://www.youtube.com/watch?v=K2VljzCC7ig" },
  { nome: "Abdominal Reto", grupoMuscular: "Core/Abdômen", equipamento: "Peso Corporal", dificuldade: "Iniciante", videoUrl: "https://www.youtube.com/watch?v=Xyd_zL4vPy4" },
  { nome: "Abdominal Remador", grupoMuscular: "Core/Abdômen", equipamento: "Peso Corporal", dificuldade: "Iniciante", videoUrl: "https://www.youtube.com/watch?v=bjvaOmlf0gc" },
  { nome: "Abdominal Bicicleta", grupoMuscular: "Core/Abdômen", equipamento: "Peso Corporal", dificuldade: "Intermediário", videoUrl: "https://www.youtube.com/watch?v=9FGilxCbdz8" },
  { nome: "Elevação de Pernas", grupoMuscular: "Core/Abdômen", equipamento: "Peso Corporal", dificuldade: "Intermediário", videoUrl: "https://www.youtube.com/watch?v=JB2oyawG9KI" },
  { nome: "Elevação de Pernas Suspenso", grupoMuscular: "Core/Abdômen", equipamento: "Peso Corporal", dificuldade: "Avançado", videoUrl: "https://www.youtube.com/watch?v=Pr1ieGZ5atk" },
  { nome: "Abdominal Declinado", grupoMuscular: "Core/Abdômen", equipamento: "Peso Corporal", dificuldade: "Intermediário", videoUrl: "https://www.youtube.com/watch?v=4mMfqWNO_n0" },
  { nome: "Abdominal Canivete (V-Up)", grupoMuscular: "Core/Abdômen", equipamento: "Peso Corporal", dificuldade: "Intermediário", videoUrl: "https://www.youtube.com/watch?v=7MdLzh_cNPw" },
  { nome: "Russian Twist", grupoMuscular: "Core/Abdômen", equipamento: "Peso Corporal/Halteres", dificuldade: "Intermediário", videoUrl: "https://www.youtube.com/watch?v=wkD8rjkodUI" },
  { nome: "Mountain Climbers", grupoMuscular: "Core/Abdômen", equipamento: "Peso Corporal", dificuldade: "Iniciante", videoUrl: "https://www.youtube.com/watch?v=nmwgirgXLYM" },
  { nome: "Dead Bug", grupoMuscular: "Core/Abdômen", equipamento: "Peso Corporal", dificuldade: "Iniciante", videoUrl: "https://www.youtube.com/watch?v=g_BYB0R-4Ws" },
  { nome: "Prancha com Toque no Ombro", grupoMuscular: "Core/Abdômen", equipamento: "Peso Corporal", dificuldade: "Intermediário", videoUrl: "https://www.youtube.com/watch?v=YqgQxYJKw3E" },
  { nome: "Abdominal no Cabo Alto", grupoMuscular: "Core/Abdômen", equipamento: "Cabo", dificuldade: "Intermediário", videoUrl: "https://www.youtube.com/watch?v=RE1HUOU8E3g" },
  { nome: "Roda Abdominal", grupoMuscular: "Core/Abdômen", equipamento: "Máquina", dificuldade: "Avançado", videoUrl: "https://www.youtube.com/watch?v=V0RcNkXqd4k" },

  // PANTURRILHAS
  { nome: "Panturrilha em Pé na Máquina", grupoMuscular: "Panturrilhas", equipamento: "Máquina", dificuldade: "Iniciante", videoUrl: "https://www.youtube.com/watch?v=JbyjNymZs2I" },
  { nome: "Panturrilha Sentado", grupoMuscular: "Panturrilhas", equipamento: "Máquina", dificuldade: "Iniciante", videoUrl: "https://www.youtube.com/watch?v=gwLzBJYoWlI" },
  { nome: "Panturrilha no Leg Press", grupoMuscular: "Panturrilhas", equipamento: "Máquina", dificuldade: "Iniciante", videoUrl: "https://www.youtube.com/watch?v=H-UvfN3Gs7c" },
  { nome: "Panturrilha Unilateral", grupoMuscular: "Panturrilhas", equipamento: "Peso Corporal/Halteres", dificuldade: "Intermediário", videoUrl: "https://www.youtube.com/watch?v=u4BNCBzMXec" },
  { nome: "Panturrilha com Halteres", grupoMuscular: "Panturrilhas", equipamento: "Halteres", dificuldade: "Iniciante", videoUrl: "https://www.youtube.com/watch?v=3j_EPYJ3_kg" },

  // EXTRAS - VARIAÇÕES ESPECÍFICAS (15 exercícios)
  { nome: "High Row no Cabo no Banco", grupoMuscular: "Costas", equipamento: "Cabo", dificuldade: "Intermediário", videoUrl: "https://www.youtube.com/watch?v=hS9gqj_7x_c" },
  { nome: "Remada Articulada Fechada Unilateral", grupoMuscular: "Costas", equipamento: "Máquina", dificuldade: "Intermediário", videoUrl: "https://www.youtube.com/watch?v=rBv6vN6oNlI" },
  { nome: "Rosca Baesiana na Polia", grupoMuscular: "Braços - Bíceps", equipamento: "Cabo", dificuldade: "Avançado", videoUrl: "https://www.youtube.com/watch?v=p1hD7j0o0fU" },
  { nome: "Rosca Superman", grupoMuscular: "Braços - Bíceps", equipamento: "Cabo", dificuldade: "Intermediário", videoUrl: "https://www.youtube.com/watch?v=F01S9e-w4D4" },
  { nome: "Tríceps Paralela na Máquina", grupoMuscular: "Braços - Tríceps", equipamento: "Máquina", dificuldade: "Iniciante", videoUrl: "https://www.youtube.com/watch?v=Yf1e5nB6k00" },
  { nome: "Tríceps Francês na Polia", grupoMuscular: "Braços - Tríceps", equipamento: "Cabo", dificuldade: "Intermediário", videoUrl: "https://www.youtube.com/watch?v=Z_a7-r585Dk" },
  { nome: "Tríceps Testa na Polia", grupoMuscular: "Braços - Tríceps", equipamento: "Cabo", dificuldade: "Intermediário", videoUrl: "https://www.youtube.com/watch?v=V802H18cRws" },
  { nome: "Supino Reto no Smith", grupoMuscular: "Peito", equipamento: "Máquina (Smith)", dificuldade: "Intermediário", videoUrl: "https://www.youtube.com/watch?v=DnkM-Wp2WlA" },
  { nome: "Supino Inclinado no Smith", grupoMuscular: "Peito", equipamento: "Máquina (Smith)", dificuldade: "Intermediário", videoUrl: "https://www.youtube.com/watch?v=TzT8X8_Kk8c" },
  { nome: "Supino Declinado na Máquina", grupoMuscular: "Peito", equipamento: "Máquina", dificuldade: "Iniciante", videoUrl: "https://www.youtube.com/watch?v=3n-208N5N48" },
  { nome: "Supino Inclinado na Máquina", grupoMuscular: "Peito", equipamento: "Máquina", dificuldade: "Iniciante", videoUrl: "https://www.youtube.com/watch?v=KzXgK_K3cHg" },
  { nome: "Desenvolvimento no Smith", grupoMuscular: "Ombros", equipamento: "Máquina (Smith)", dificuldade: "Intermediário", videoUrl: "https://www.youtube.com/watch?v=cEwP8U0x47k" },
  { nome: "Remada Curvada no Smith", grupoMuscular: "Costas", equipamento: "Máquina (Smith)", dificuldade: "Intermediário", videoUrl: "https://www.youtube.com/watch?v=wX-yUf4w2Yg" },
  { nome: "Afundo no Smith", grupoMuscular: "Pernas - Quadríceps", equipamento: "Máquina (Smith)", dificuldade: "Intermediário", videoUrl: "https://www.youtube.com/watch?v=6PZ_vD3B03M" },
  { nome: "Agachamento Sumô com Halter", grupoMuscular: "Pernas - Quadríceps", equipamento: "Halteres", dificuldade: "Intermediário", videoUrl: "https://www.youtube.com/watch?v=mD0kY8P04yQ" }
].map(ex => ({
  ...ex,
  descricao: "",
  videoUrlPadrao: ex.videoUrl,
  criadoPor: "system",
  ativo: true
}));
