import type { Exercise } from "../types";

export const firestoreExercises: Exercise[] = [
  {
    "exerciseId": "0Tf5V6IPrjMyhA58DDsQ",
    "ativo": true,
    "descricao": "",
    "equipamento": "Corda de Pular",
    "dificuldade": "Intermediário",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Corda%20de%20Pular%20execucao%20correta",
    "criadoPor": "system",
    "grupoMuscular": "Cardio / Aeróbico",
    "nome": "Corda de Pular",
    "videoUrl": "https://www.youtube.com/watch?v=x7UoXg3o2kY"
  },
  {
    "exerciseId": "0bKejJvgK6SLmjDv23wa",
    "videoUrl": "https://www.youtube.com/watch?v=VmB1G1K7v94",
    "criadoPor": "system",
    "grupoMuscular": "Peito",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Supino%20com%20Halteres%20execucao%20correta",
    "equipamento": "Halteres",
    "ativo": true,
    "dificuldade": "Iniciante",
    "descricao": "",
    "nome": "Supino com Halteres"
  },
  {
    "exerciseId": "12IVU440pL7lpcYFOjkv",
    "equipamento": "Elíptico",
    "dificuldade": "Iniciante",
    "criadoPor": "system",
    "grupoMuscular": "Cardio / Aeróbico",
    "ativo": true,
    "descricao": "",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20El%C3%ADptico%20(Transport)%20execucao%20correta",
    "videoUrl": "https://www.youtube.com/watch?v=WzF2k81jHag",
    "nome": "Elíptico (Transport)"
  },
  {
    "exerciseId": "1ajyYwRT6LlWGmJ4o6fz",
    "criadoPor": "system",
    "grupoMuscular": "Pernas - Quadríceps",
    "nome": "Afundo no Smith",
    "videoUrl": "https://www.youtube.com/watch?v=6PZ_vD3B03M",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Afundo%20no%20Smith%20execucao%20correta",
    "equipamento": "Máquina (Smith)",
    "descricao": "",
    "dificuldade": "Intermediário",
    "ativo": true
  },
  {
    "exerciseId": "1m1eC5KywU7vo5choRv6",
    "nome": "Supino Fechado",
    "videoUrl": "https://www.youtube.com/watch?v=nEF0bv2FW94",
    "grupoMuscular": "Braços - Tríceps",
    "descricao": "",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Supino%20Fechado%20execucao%20correta",
    "dificuldade": "Intermediário",
    "ativo": true,
    "equipamento": "Barra",
    "criadoPor": "system"
  },
  {
    "exerciseId": "2tOxjQdgHvLS8BohMqJf",
    "descricao": "",
    "ativo": true,
    "equipamento": "Máquina",
    "dificuldade": "Iniciante",
    "videoUrl": "https://www.youtube.com/watch?v=CAwf7n6Luuc",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Puxada%20Alta%20execucao%20correta",
    "criadoPor": "system",
    "nome": "Puxada Alta",
    "grupoMuscular": "Costas"
  },
  {
    "exerciseId": "3cdquHr6h6uB9O9v2KJa",
    "ativo": true,
    "videoUrl": "https://www.youtube.com/watch?v=8p6W7Zwcqzs",
    "dificuldade": "Iniciante",
    "equipamento": "Cabo",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Rosca%20no%20Cabo%20execucao%20correta",
    "criadoPor": "system",
    "nome": "Rosca no Cabo",
    "grupoMuscular": "Braços - Bíceps",
    "descricao": ""
  },
  {
    "exerciseId": "43wdQ98w81EDovqp3lK5",
    "nome": "Puxada Alta Supinada",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Puxada%20Alta%20Supinada%20execucao%20correta",
    "ativo": true,
    "videoUrl": "https://www.youtube.com/watch?v=rT1nGjGM2p8",
    "descricao": "",
    "equipamento": "Máquina",
    "dificuldade": "Iniciante",
    "grupoMuscular": "Costas",
    "criadoPor": "system"
  },
  {
    "exerciseId": "4XVkT95NaSTO8Op1cm7V",
    "nome": "Tríceps Testa na Polia",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Tr%C3%ADceps%20Testa%20na%20Polia%20execucao%20correta",
    "ativo": true,
    "videoUrl": "https://www.youtube.com/watch?v=V802H18cRws",
    "descricao": "",
    "equipamento": "Cabo",
    "dificuldade": "Intermediário",
    "grupoMuscular": "Braços - Tríceps",
    "criadoPor": "system"
  },
  {
    "exerciseId": "4nUqWxxgERN9GN4zmG7D",
    "videoUrl": "https://www.youtube.com/watch?v=1uDiW5--rAE",
    "nome": "Stiff com Barra",
    "grupoMuscular": "Pernas - Posteriores",
    "criadoPor": "system",
    "equipamento": "Barra",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Stiff%20com%20Barra%20execucao%20correta",
    "dificuldade": "Intermediário",
    "descricao": "",
    "ativo": true
  },
  {
    "exerciseId": "4vct7VrnmYxOY1sXBsjl",
    "descricao": "",
    "ativo": true,
    "videoUrl": "https://www.youtube.com/watch?v=YyvSfVjQeL0",
    "grupoMuscular": "Pernas - Quadríceps",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Cadeira%20Extensora%20execucao%20correta",
    "criadoPor": "system",
    "nome": "Cadeira Extensora",
    "equipamento": "Máquina",
    "dificuldade": "Iniciante"
  },
  {
    "exerciseId": "5REJdyHRtdbtIx8rrWU9",
    "descricao": "",
    "ativo": true,
    "videoUrl": "https://www.youtube.com/watch?v=ytGaGIn3SjE",
    "grupoMuscular": "Costas",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Levantamento%20Terra%20(Deadlift)%20execucao%20correta",
    "criadoPor": "system",
    "nome": "Levantamento Terra (Deadlift)",
    "equipamento": "Barra",
    "dificuldade": "Avançado"
  },
  {
    "exerciseId": "5kujglGs8Co5fDMqtQgt",
    "videoUrl": "https://www.youtube.com/watch?v=o0RMHlPaLlg",
    "dificuldade": "Iniciante",
    "ativo": true,
    "equipamento": "Máquina",
    "descricao": "",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Leg%20Press%20Horizontal%20execucao%20correta",
    "nome": "Leg Press Horizontal",
    "grupoMuscular": "Pernas - Quadríceps",
    "criadoPor": "system"
  },
  {
    "exerciseId": "5w0QCKBnemQf9eg4TuQN",
    "equipamento": "Halteres",
    "dificuldade": "Iniciante",
    "videoUrl": "https://www.youtube.com/watch?v=3j_EPYJ3_kg",
    "ativo": true,
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Panturrilha%20com%20Halteres%20execucao%20correta",
    "criadoPor": "system",
    "nome": "Panturrilha com Halteres",
    "grupoMuscular": "Panturrilhas",
    "descricao": ""
  },
  {
    "exerciseId": "6wYPuHbKP6Ukq6F6FEaI",
    "videoUrl": "https://www.youtube.com/watch?v=dVHdrd03-nc",
    "grupoMuscular": "Pernas - Quadríceps",
    "descricao": "",
    "ativo": true,
    "nome": "Step Up",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Step%20Up%20execucao%20correta",
    "criadoPor": "system",
    "equipamento": "Halteres",
    "dificuldade": "Intermediário"
  },
  {
    "exerciseId": "7JsZmSDgerRNhrbzIQGk",
    "equipamento": "Barra",
    "dificuldade": "Intermediário",
    "ativo": true,
    "criadoPor": "system",
    "videoUrl": "https://www.youtube.com/watch?v=Auu7S3HQbJs",
    "nome": "Remada Curvada Supinada",
    "descricao": "",
    "grupoMuscular": "Costas",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Remada%20Curvada%20Supinada%20execucao%20correta"
  },
  {
    "exerciseId": "7lfJiB9mM34Pf2OYhhoZ",
    "equipamento": "Máquina",
    "ativo": true,
    "dificuldade": "Iniciante",
    "criadoPor": "system",
    "videoUrl": "https://www.youtube.com/watch?v=_JJQi_MYW_E",
    "nome": "Crucifixo Inverso na Máquina",
    "descricao": "",
    "grupoMuscular": "Ombros",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Crucifixo%20Inverso%20na%20M%C3%A1quina%20execucao%20correta"
  },
  {
    "exerciseId": "8QtZh5DLZS67o4zh0mZV",
    "ativo": true,
    "grupoMuscular": "Costas",
    "criadoPor": "system",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Remada%20Cavalinho%20execucao%20correta",
    "nome": "Remada Cavalinho",
    "dificuldade": "Intermediário",
    "descricao": "",
    "equipamento": "Barra",
    "videoUrl": "https://www.youtube.com/watch?v=j3Igk5nyZE4"
  },
  {
    "exerciseId": "8gIn44jHP3491kS29TX1",
    "nome": "Rosca Martelo",
    "dificuldade": "Iniciante",
    "grupoMuscular": "Braços - Bíceps",
    "ativo": true,
    "equipamento": "Halteres",
    "criadoPor": "system",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Rosca%20Martelo%20execucao%20correta",
    "videoUrl": "https://www.youtube.com/watch?v=zC3nLlEvin4",
    "descricao": ""
  },
  {
    "exerciseId": "9Cth1P0IjqqFBTLUZGrI",
    "nome": "Tríceps Testa (Skull Crusher)",
    "dificuldade": "Intermediário",
    "ativo": true,
    "grupoMuscular": "Braços - Tríceps",
    "criadoPor": "system",
    "equipamento": "Barra",
    "videoUrl": "https://www.youtube.com/watch?v=d_KZxkY_0cM",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Tr%C3%ADceps%20Testa%20(Skull%20Crusher)%20execucao%20correta",
    "descricao": ""
  },
  {
    "exerciseId": "9Mvh1KKMuDpZp5hIZiEl",
    "ativo": true,
    "descricao": "",
    "grupoMuscular": "Peito",
    "videoUrl": "https://www.youtube.com/watch?v=sGl1IYdCT5w",
    "criadoPor": "system",
    "equipamento": "Halteres",
    "dificuldade": "Intermediário",
    "nome": "Pullover com Halter",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Pullover%20com%20Halter%20execucao%20correta"
  },
  {
    "exerciseId": "9Ox2Vr7LsBzQstJFnw7z",
    "criadoPor": "system",
    "ativo": true,
    "nome": "Crossover",
    "descricao": "",
    "grupoMuscular": "Peito",
    "equipamento": "Cabo",
    "dificuldade": "Intermediário",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Crossover%20execucao%20correta",
    "videoUrl": "https://www.youtube.com/watch?v=taI4XduLpTk"
  },
  {
    "exerciseId": "ALayw69NfGd9Xhxw92KZ",
    "grupoMuscular": "Peito",
    "descricao": "",
    "videoUrl": "https://www.youtube.com/watch?v=0326dy_-CzM",
    "dificuldade": "Iniciante",
    "equipamento": "Peso Corporal",
    "ativo": true,
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Mergulho%20(Dips)%20no%20Banco%20execucao%20correta",
    "criadoPor": "system",
    "nome": "Mergulho (Dips) no Banco"
  },
  {
    "exerciseId": "ATtLaEZ4DO8HC6r6k1ld",
    "videoUrl": "https://www.youtube.com/watch?v=7MdLzh_cNPw",
    "criadoPor": "system",
    "nome": "Abdominal Canivete (V-Up)",
    "grupoMuscular": "Core/Abdômen",
    "descricao": "",
    "equipamento": "Peso Corporal",
    "ativo": true,
    "dificuldade": "Intermediário",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Abdominal%20Canivete%20(V-Up)%20execucao%20correta"
  },
  {
    "exerciseId": "AbrdjnEMPLihrmgNrco0",
    "equipamento": "Máquina",
    "descricao": "",
    "nome": "Remada Baixa",
    "dificuldade": "Iniciante",
    "ativo": true,
    "videoUrl": "https://www.youtube.com/watch?v=GZbfZ033f74",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Remada%20Baixa%20execucao%20correta",
    "criadoPor": "system",
    "grupoMuscular": "Costas"
  },
  {
    "exerciseId": "BBYhNHN3DND5cz5v4rRB",
    "descricao": "",
    "equipamento": "Máquina",
    "nome": "Tríceps Paralela na Máquina",
    "dificuldade": "Iniciante",
    "ativo": true,
    "videoUrl": "https://www.youtube.com/watch?v=Yf1e5nB6k00",
    "criadoPor": "system",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Tr%C3%ADceps%20Paralela%20na%20M%C3%A1quina%20execucao%20correta",
    "grupoMuscular": "Braços - Tríceps"
  },
  {
    "exerciseId": "ByDXFMv2swNPa9K9KBRe",
    "descricao": "",
    "nome": "Barra Fixa (Pull-up)",
    "equipamento": "Peso Corporal",
    "dificuldade": "Avançado",
    "grupoMuscular": "Costas",
    "videoUrl": "https://www.youtube.com/watch?v=eGo4IYlbE5g",
    "criadoPor": "system",
    "ativo": true,
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Barra%20Fixa%20(Pull-up)%20execucao%20correta"
  },
  {
    "exerciseId": "CiSCF31HiNBb3SSVHFDG",
    "dificuldade": "Intermediário",
    "equipamento": "Cabo",
    "descricao": "",
    "grupoMuscular": "Core/Abdômen",
    "ativo": true,
    "videoUrl": "https://www.youtube.com/watch?v=RE1HUOU8E3g",
    "nome": "Abdominal no Cabo Alto",
    "criadoPor": "system",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Abdominal%20no%20Cabo%20Alto%20execucao%20correta"
  },
  {
    "exerciseId": "DLnBmH0hT11EiFgZdSMi",
    "nome": "Afundo (Lunge)",
    "equipamento": "Halteres",
    "dificuldade": "Intermediário",
    "criadoPor": "system",
    "ativo": true,
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Afundo%20(Lunge)%20execucao%20correta",
    "grupoMuscular": "Pernas - Quadríceps",
    "videoUrl": "https://www.youtube.com/watch?v=QOVaHwm-Q6U",
    "descricao": ""
  },
  {
    "exerciseId": "DMuV3cBp5E2bpZkn33QE",
    "equipamento": "Halteres",
    "nome": "Rosca Alternada com Halteres",
    "dificuldade": "Iniciante",
    "criadoPor": "system",
    "ativo": true,
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Rosca%20Alternada%20com%20Halteres%20execucao%20correta",
    "grupoMuscular": "Braços - Bíceps",
    "videoUrl": "https://www.youtube.com/watch?v=G6feTR1uIG4",
    "descricao": ""
  },
  {
    "exerciseId": "Da0NWC100sno3ElKz82v",
    "dificuldade": "Iniciante",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Hiperextens%C3%A3o%20Lombar%20execucao%20correta",
    "equipamento": "Peso Corporal",
    "criadoPor": "system",
    "ativo": true,
    "descricao": "",
    "videoUrl": "https://www.youtube.com/watch?v=J1hMoI4I5X8",
    "grupoMuscular": "Costas",
    "nome": "Hiperextensão Lombar"
  },
  {
    "exerciseId": "DjCrxWBNYlqG7zwPBegX",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Supino%20na%20M%C3%A1quina%20execucao%20correta",
    "nome": "Supino na Máquina",
    "descricao": "",
    "videoUrl": "https://www.youtube.com/watch?v=xUm0BiZCWlQ",
    "grupoMuscular": "Peito",
    "ativo": true,
    "criadoPor": "system",
    "equipamento": "Máquina",
    "dificuldade": "Iniciante"
  },
  {
    "exerciseId": "EiWoGRgtm9GIO6JwBeAb",
    "criadoPor": "system",
    "dificuldade": "Iniciante",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Ponte%20(Hip%20Bridge)%20execucao%20correta",
    "equipamento": "Peso Corporal",
    "nome": "Ponte (Hip Bridge)",
    "descricao": "",
    "videoUrl": "https://www.youtube.com/watch?v=0Vz5MUfUizg",
    "grupoMuscular": "Pernas - Posteriores",
    "ativo": true
  },
  {
    "exerciseId": "EwHXOyqVlE8odFKCQ1uv",
    "descricao": "",
    "grupoMuscular": "Peito",
    "equipamento": "Peso Corporal",
    "dificuldade": "Intermediário",
    "nome": "Flexão Declinada",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Flex%C3%A3o%20Declinada%20execucao%20correta",
    "videoUrl": "https://www.youtube.com/watch?v=Yb1H_GN5Cw4",
    "criadoPor": "system",
    "ativo": true
  },
  {
    "exerciseId": "F3iYKGKOB2K6CdClfC2M",
    "descricao": "",
    "nome": "Flexão de Braço",
    "grupoMuscular": "Peito",
    "ativo": true,
    "criadoPor": "system",
    "dificuldade": "Iniciante",
    "equipamento": "Peso Corporal",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Flex%C3%A3o%20de%20Bra%C3%A7o%20execucao%20correta",
    "videoUrl": "https://www.youtube.com/watch?v=IODxDxX7oi4"
  },
  {
    "exerciseId": "G1LckeySuYIv2YEkVbqd",
    "descricao": "",
    "equipamento": "Máquina (Smith)",
    "ativo": true,
    "dificuldade": "Intermediário",
    "criadoPor": "system",
    "nome": "Supino Reto no Smith",
    "videoUrl": "https://www.youtube.com/watch?v=DnkM-Wp2WlA",
    "grupoMuscular": "Peito",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Supino%20Reto%20no%20Smith%20execucao%20correta"
  },
  {
    "exerciseId": "G6buW6JXFUSePcbsucka",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Crucifixo%20com%20Halteres%20execucao%20correta",
    "nome": "Crucifixo com Halteres",
    "grupoMuscular": "Peito",
    "criadoPor": "system",
    "dificuldade": "Iniciante",
    "ativo": true,
    "videoUrl": "https://www.youtube.com/watch?v=eozdVDA78K0",
    "equipamento": "Halteres",
    "descricao": ""
  },
  {
    "exerciseId": "GWppnH1vbxMiAlIQnElk",
    "nome": "Tríceps Francês na Polia",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Tr%C3%ADceps%20Franc%C3%AAs%20na%20Polia%20execucao%20correta",
    "grupoMuscular": "Braços - Tríceps",
    "criadoPor": "system",
    "dificuldade": "Intermediário",
    "ativo": true,
    "equipamento": "Cabo",
    "videoUrl": "https://www.youtube.com/watch?v=Z_a7-r585Dk",
    "descricao": ""
  },
  {
    "exerciseId": "GjYO6TzLdzDWFiXI1YdQ",
    "equipamento": "Halteres",
    "dificuldade": "Iniciante",
    "descricao": "",
    "nome": "Elevação Frontal",
    "ativo": true,
    "grupoMuscular": "Ombros",
    "criadoPor": "system",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Eleva%C3%A7%C3%A3o%20Frontal%20execucao%20correta",
    "videoUrl": "https://www.youtube.com/watch?v=qkx-rpgh27w"
  },
  {
    "exerciseId": "IhOugFYfB61zcBBbdx73",
    "ativo": true,
    "videoUrl": "https://www.youtube.com/watch?v=yQXnOuQqKYc",
    "grupoMuscular": "Pernas - Quadríceps",
    "criadoPor": "system",
    "nome": "Leg Press 45°",
    "dificuldade": "Iniciante",
    "equipamento": "Máquina",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Leg%20Press%2045%C2%B0%20execucao%20correta",
    "descricao": ""
  },
  {
    "exerciseId": "IuQ6VpZrabFhSxlPRION",
    "ativo": true,
    "grupoMuscular": "Cardio / Aeróbico",
    "videoUrl": "https://www.youtube.com/watch?v=kF7p0B_Yd98",
    "criadoPor": "system",
    "nome": "Escada Simulada (Stairmaster)",
    "dificuldade": "Intermediário",
    "equipamento": "Escada Simulada",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Escada%20Simulada%20(Stairmaster)%20execucao%20correta",
    "descricao": ""
  },
  {
    "exerciseId": "IxKGauXyfFkIiRSsmBPs",
    "nome": "Abdominal Remador",
    "descricao": "",
    "grupoMuscular": "Core/Abdômen",
    "videoUrl": "https://www.youtube.com/watch?v=bjvaOmlf0gc",
    "ativo": true,
    "criadoPor": "system",
    "equipamento": "Peso Corporal",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Abdominal%20Remador%20execucao%20correta",
    "dificuldade": "Iniciante"
  },
  {
    "exerciseId": "J7xdCEPIcwig7wCB0Kb4",
    "nome": "Peck Deck (Voador)",
    "descricao": "",
    "grupoMuscular": "Peito",
    "ativo": true,
    "videoUrl": "https://www.youtube.com/watch?v=Z71bFZrVCVo",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Peck%20Deck%20(Voador)%20execucao%20correta",
    "criadoPor": "system",
    "dificuldade": "Iniciante",
    "equipamento": "Máquina"
  },
  {
    "exerciseId": "JqdiWFMNLCN6Qs6hZcvY",
    "videoUrl": "https://www.youtube.com/watch?v=QkvGC4MnOfM",
    "descricao": "",
    "nome": "Cadeira Flexora",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Cadeira%20Flexora%20execucao%20correta",
    "ativo": true,
    "dificuldade": "Iniciante",
    "grupoMuscular": "Pernas - Posteriores",
    "criadoPor": "system",
    "equipamento": "Máquina"
  },
  {
    "exerciseId": "K3bAsS9oftHA4QPb6p8h",
    "equipamento": "Barra",
    "descricao": "",
    "dificuldade": "Intermediário",
    "videoUrl": "https://www.youtube.com/watch?v=nRgxYX2Ve9w",
    "nome": "Rosca Inversa",
    "grupoMuscular": "Braços - Bíceps",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Rosca%20Inversa%20execucao%20correta",
    "criadoPor": "system",
    "ativo": true
  },
  {
    "exerciseId": "KZB31M4qHJsc49vLP685",
    "videoUrl": "https://www.youtube.com/watch?v=6Z15_WdXmVw",
    "descricao": "",
    "nome": "Desenvolvimento Arnold",
    "dificuldade": "Intermediário",
    "equipamento": "Halteres",
    "ativo": true,
    "grupoMuscular": "Ombros",
    "criadoPor": "system",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Desenvolvimento%20Arnold%20execucao%20correta"
  },
  {
    "exerciseId": "LJbWyCkrUGjOy8Ksard3",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Russian%20Twist%20execucao%20correta",
    "videoUrl": "https://www.youtube.com/watch?v=wkD8rjkodUI",
    "ativo": true,
    "grupoMuscular": "Core/Abdômen",
    "descricao": "",
    "nome": "Russian Twist",
    "dificuldade": "Intermediário",
    "equipamento": "Peso Corporal/Halteres",
    "criadoPor": "system"
  },
  {
    "exerciseId": "MKN0ypw1w5LY67UIPfYK",
    "descricao": "",
    "equipamento": "Máquina",
    "dificuldade": "Iniciante",
    "nome": "Panturrilha Sentado",
    "criadoPor": "system",
    "ativo": true,
    "grupoMuscular": "Panturrilhas",
    "videoUrl": "https://www.youtube.com/watch?v=gwLzBJYoWlI",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Panturrilha%20Sentado%20execucao%20correta"
  },
  {
    "exerciseId": "MOKtkk9IG9HferKjB8MM",
    "descricao": "",
    "equipamento": "Cabo",
    "dificuldade": "Intermediário",
    "criadoPor": "system",
    "nome": "Elevação Lateral no Cabo",
    "ativo": true,
    "videoUrl": "https://www.youtube.com/watch?v=3bJHvKshZP8",
    "grupoMuscular": "Ombros",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Eleva%C3%A7%C3%A3o%20Lateral%20no%20Cabo%20execucao%20correta"
  },
  {
    "exerciseId": "NGeu64QTw4YaXiHUvHwB",
    "criadoPor": "system",
    "videoUrl": "https://www.youtube.com/watch?v=NkMHIH_LTiE",
    "ativo": true,
    "dificuldade": "Avançado",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Agachamento%20Frontal%20execucao%20correta",
    "equipamento": "Barra",
    "nome": "Agachamento Frontal",
    "descricao": "",
    "grupoMuscular": "Pernas - Quadríceps"
  },
  {
    "exerciseId": "NIeJyLRt1jKX67LtnT1A",
    "criadoPor": "system",
    "videoUrl": "https://www.youtube.com/watch?v=8iPEnn-ltC8",
    "ativo": true,
    "dificuldade": "Iniciante",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Supino%20Inclinado%20com%20Halteres%20execucao%20correta",
    "equipamento": "Halteres",
    "descricao": "",
    "nome": "Supino Inclinado com Halteres",
    "grupoMuscular": "Peito"
  },
  {
    "exerciseId": "O4hW4885EyHT1zTPN1i2",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Rosca%20Baesiana%20na%20Polia%20execucao%20correta",
    "descricao": "",
    "grupoMuscular": "Braços - Bíceps",
    "nome": "Rosca Baesiana na Polia",
    "criadoPor": "system",
    "ativo": true,
    "equipamento": "Cabo",
    "videoUrl": "https://www.youtube.com/watch?v=p1hD7j0o0fU",
    "dificuldade": "Avançado"
  },
  {
    "exerciseId": "OB1tQSfyTBQj6XyTo8Gj",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Supino%20Inclinado%20com%20Barra%20execucao%20correta",
    "grupoMuscular": "Peito",
    "descricao": "",
    "nome": "Supino Inclinado com Barra",
    "criadoPor": "system",
    "ativo": true,
    "equipamento": "Barra",
    "videoUrl": "https://www.youtube.com/watch?v=jb5LQYJPVjo",
    "dificuldade": "Intermediário"
  },
  {
    "exerciseId": "OWWMUlHxsW0gdRFTgrX5",
    "nome": "Dead Bug",
    "dificuldade": "Iniciante",
    "criadoPor": "system",
    "equipamento": "Peso Corporal",
    "ativo": true,
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Dead%20Bug%20execucao%20correta",
    "videoUrl": "https://www.youtube.com/watch?v=g_BYB0R-4Ws",
    "descricao": "",
    "grupoMuscular": "Core/Abdômen"
  },
  {
    "exerciseId": "Ot1w6fzhg6Hm99itoVYN",
    "equipamento": "Cabo",
    "criadoPor": "system",
    "dificuldade": "Intermediário",
    "ativo": true,
    "nome": "Coice no Cabo",
    "descricao": "",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Coice%20no%20Cabo%20execucao%20correta",
    "videoUrl": "https://www.youtube.com/watch?v=b-8Fzyf-7Xg",
    "grupoMuscular": "Pernas - Posteriores"
  },
  {
    "exerciseId": "Ouf1cIL4rpUXcbRZqVuG",
    "criadoPor": "system",
    "equipamento": "Máquina",
    "dificuldade": "Iniciante",
    "ativo": true,
    "nome": "Supino Inclinado na Máquina",
    "descricao": "",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Supino%20Inclinado%20na%20M%C3%A1quina%20execucao%20correta",
    "videoUrl": "https://www.youtube.com/watch?v=KzXgK_K3cHg",
    "grupoMuscular": "Peito"
  },
  {
    "exerciseId": "OxpCd3csweCaX1TKOHOg",
    "criadoPor": "system",
    "equipamento": "Barra",
    "dificuldade": "Iniciante",
    "grupoMuscular": "Braços - Bíceps",
    "videoUrl": "https://www.youtube.com/watch?v=kwG2ipFRgfo",
    "descricao": "",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Rosca%20Direta%20com%20Barra%20execucao%20correta",
    "ativo": true,
    "nome": "Rosca Direta com Barra"
  },
  {
    "exerciseId": "PE3CBEPpQTToLzK3f8WN",
    "criadoPor": "system",
    "equipamento": "Halteres",
    "dificuldade": "Intermediário",
    "grupoMuscular": "Pernas - Quadríceps",
    "videoUrl": "https://www.youtube.com/watch?v=mD0kY8P04yQ",
    "descricao": "",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Agachamento%20Sum%C3%B4%20com%20Halter%20execucao%20correta",
    "ativo": true,
    "nome": "Agachamento Sumô com Halter"
  },
  {
    "exerciseId": "PNcCsPTsjudrctwb3Xtb",
    "grupoMuscular": "Pernas - Quadríceps",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Agachamento%20Sum%C3%B4%20execucao%20correta",
    "videoUrl": "https://www.youtube.com/watch?v=0ry_-l0JuPc",
    "ativo": true,
    "criadoPor": "system",
    "equipamento": "Halteres",
    "descricao": "",
    "dificuldade": "Intermediário",
    "nome": "Agachamento Sumô"
  },
  {
    "exerciseId": "PREXB1EBmxDgAzv0F78M",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Eleva%C3%A7%C3%A3o%20de%20Pernas%20execucao%20correta",
    "grupoMuscular": "Core/Abdômen",
    "criadoPor": "system",
    "ativo": true,
    "videoUrl": "https://www.youtube.com/watch?v=JB2oyawG9KI",
    "equipamento": "Peso Corporal",
    "descricao": "",
    "dificuldade": "Intermediário",
    "nome": "Elevação de Pernas"
  },
  {
    "exerciseId": "PcOf5CeHncOaUWwNIQVw",
    "nome": "Remada Alta",
    "criadoPor": "system",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Remada%20Alta%20execucao%20correta",
    "grupoMuscular": "Ombros",
    "ativo": true,
    "equipamento": "Barra",
    "dificuldade": "Intermediário",
    "descricao": "",
    "videoUrl": "https://www.youtube.com/watch?v=qkrUv-7s8Ik"
  },
  {
    "exerciseId": "QX9iMvm07NOuzBorfUMc",
    "equipamento": "Halteres",
    "dificuldade": "Intermediário",
    "nome": "Afundo Búlgaro",
    "grupoMuscular": "Pernas - Quadríceps",
    "videoUrl": "https://www.youtube.com/watch?v=2C-uNgKwPLE",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Afundo%20B%C3%BAlgaro%20execucao%20correta",
    "criadoPor": "system",
    "ativo": true,
    "descricao": ""
  },
  {
    "exerciseId": "QYsrtk7O1BsAGLNLON8T",
    "equipamento": "Esteira",
    "nome": "Esteira (Caminhada/Corrida)",
    "dificuldade": "Iniciante",
    "grupoMuscular": "Cardio / Aeróbico",
    "videoUrl": "https://www.youtube.com/watch?v=N6J0Mv3N5Qk",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Esteira%20(Caminhada%2FCorrida)%20execucao%20correta",
    "criadoPor": "system",
    "ativo": true,
    "descricao": ""
  },
  {
    "exerciseId": "Qna5uYjTW8maGvXFvQow",
    "descricao": "",
    "ativo": true,
    "equipamento": "Máquina",
    "dificuldade": "Iniciante",
    "criadoPor": "system",
    "nome": "Desenvolvimento na Máquina",
    "grupoMuscular": "Ombros",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Desenvolvimento%20na%20M%C3%A1quina%20execucao%20correta",
    "videoUrl": "https://www.youtube.com/watch?v=FnPgXKBUy0k"
  },
  {
    "exerciseId": "QwqNNSEDnRnH1G3GZNyl",
    "nome": "Supino Declinado na Máquina",
    "criadoPor": "system",
    "grupoMuscular": "Peito",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Supino%20Declinado%20na%20M%C3%A1quina%20execucao%20correta",
    "equipamento": "Máquina",
    "dificuldade": "Iniciante",
    "videoUrl": "https://www.youtube.com/watch?v=3n-208N5N48",
    "descricao": "",
    "ativo": true
  },
  {
    "exerciseId": "SG2UE8vp70OLnIYZ4bL5",
    "nome": "Elevação Lateral Inclinado",
    "videoUrl": "https://www.youtube.com/watch?v=WqZxT0uzAHs",
    "descricao": "",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Eleva%C3%A7%C3%A3o%20Lateral%20Inclinado%20execucao%20correta",
    "grupoMuscular": "Ombros",
    "dificuldade": "Intermediário",
    "criadoPor": "system",
    "equipamento": "Halteres",
    "ativo": true
  },
  {
    "exerciseId": "SuOZxv9Klu98wuAtCceb",
    "videoUrl": "https://www.youtube.com/watch?v=tTKY4kcP9ZI",
    "dificuldade": "Intermediário",
    "equipamento": "Halteres",
    "descricao": "",
    "ativo": true,
    "nome": "Crucifixo Inverso",
    "criadoPor": "system",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Crucifixo%20Inverso%20execucao%20correta",
    "grupoMuscular": "Ombros"
  },
  {
    "exerciseId": "Sz9McMSDA2oNbfo9htn9",
    "videoUrl": "https://www.youtube.com/watch?v=qEwKCR5JCog",
    "dificuldade": "Iniciante",
    "equipamento": "Halteres",
    "descricao": "",
    "ativo": true,
    "nome": "Desenvolvimento com Halteres",
    "criadoPor": "system",
    "grupoMuscular": "Ombros",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Desenvolvimento%20com%20Halteres%20execucao%20correta"
  },
  {
    "exerciseId": "TEYaYFKsqry7IvOxjQ1L",
    "descricao": "",
    "nome": "Rosca Superman",
    "equipamento": "Cabo",
    "dificuldade": "Intermediário",
    "ativo": true,
    "grupoMuscular": "Braços - Bíceps",
    "criadoPor": "system",
    "videoUrl": "https://www.youtube.com/watch?v=F01S9e-w4D4",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Rosca%20Superman%20execucao%20correta"
  },
  {
    "exerciseId": "U2EGyPPfvMU49eul42EI",
    "nome": "Coice com Halter",
    "dificuldade": "Iniciante",
    "criadoPor": "system",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Coice%20com%20Halter%20execucao%20correta",
    "equipamento": "Halteres",
    "videoUrl": "https://www.youtube.com/watch?v=_qJ2Urbh_34",
    "descricao": "",
    "grupoMuscular": "Braços - Tríceps",
    "ativo": true
  },
  {
    "exerciseId": "UO3124kt0BGoFIipAX1G",
    "criadoPor": "system",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Panturrilha%20Unilateral%20execucao%20correta",
    "nome": "Panturrilha Unilateral",
    "grupoMuscular": "Panturrilhas",
    "descricao": "",
    "videoUrl": "https://www.youtube.com/watch?v=u4BNCBzMXec",
    "ativo": true,
    "dificuldade": "Intermediário",
    "equipamento": "Peso Corporal/Halteres"
  },
  {
    "exerciseId": "VEMjRDvEx75j98dKVDJH",
    "ativo": true,
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Remada%20Curvada%20no%20Smith%20execucao%20correta",
    "descricao": "",
    "videoUrl": "https://www.youtube.com/watch?v=wX-yUf4w2Yg",
    "grupoMuscular": "Costas",
    "equipamento": "Máquina (Smith)",
    "dificuldade": "Intermediário",
    "criadoPor": "system",
    "nome": "Remada Curvada no Smith"
  },
  {
    "exerciseId": "VfMNBPmEKyyLMBHPYYVP",
    "ativo": true,
    "videoUrl": "https://www.youtube.com/watch?v=kBWAon7ItDw",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Remada%20Curvada%20com%20Barra%20execucao%20correta",
    "descricao": "",
    "dificuldade": "Intermediário",
    "equipamento": "Barra",
    "grupoMuscular": "Costas",
    "criadoPor": "system",
    "nome": "Remada Curvada com Barra"
  },
  {
    "exerciseId": "X0fCV1lOXw7U9p2oCHKc",
    "ativo": true,
    "videoUrl": "https://www.youtube.com/watch?v=YbX7Wd8jQ-Q",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Tr%C3%ADceps%20Franc%C3%AAs%20com%20Halteres%20execucao%20correta",
    "descricao": "",
    "dificuldade": "Intermediário",
    "equipamento": "Halteres",
    "grupoMuscular": "Braços - Tríceps",
    "criadoPor": "system",
    "nome": "Tríceps Francês com Halteres"
  },
  {
    "exerciseId": "X5NSzEwTNUUdpzueuVwH",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Rosca%20Direta%20com%20Barra%20W%20execucao%20correta",
    "grupoMuscular": "Braços - Bíceps",
    "ativo": true,
    "criadoPor": "system",
    "videoUrl": "https://www.youtube.com/watch?v=soxrZlIl35U",
    "nome": "Rosca Direta com Barra W",
    "dificuldade": "Iniciante",
    "equipamento": "Barra",
    "descricao": ""
  },
  {
    "exerciseId": "X8Sh90AkmaxbKOJqrL6c",
    "videoUrl": "https://www.youtube.com/watch?v=9hNmjGZYy8s",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Stiff%20com%20Halteres%20execucao%20correta",
    "dificuldade": "Intermediário",
    "equipamento": "Halteres",
    "descricao": "",
    "nome": "Stiff com Halteres",
    "grupoMuscular": "Pernas - Posteriores",
    "ativo": true,
    "criadoPor": "system"
  },
  {
    "exerciseId": "XUPboGQCmDRgDqr0f6mx",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Tr%C3%ADceps%20Supinado%20execucao%20correta",
    "dificuldade": "Intermediário",
    "equipamento": "Barra",
    "ativo": true,
    "descricao": "",
    "videoUrl": "https://www.youtube.com/watch?v=y7-2YxW7dL0",
    "nome": "Tríceps Supinado",
    "grupoMuscular": "Braços - Tríceps",
    "criadoPor": "system"
  },
  {
    "exerciseId": "XrLpRbL7GAv8FABhumkM",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Panturrilha%20em%20P%C3%A9%20na%20M%C3%A1quina%20execucao%20correta",
    "dificuldade": "Iniciante",
    "equipamento": "Máquina",
    "descricao": "",
    "ativo": true,
    "videoUrl": "https://www.youtube.com/watch?v=JbyjNymZs2I",
    "nome": "Panturrilha em Pé na Máquina",
    "grupoMuscular": "Panturrilhas",
    "criadoPor": "system"
  },
  {
    "exerciseId": "ZS0Ilu0Iz1N4OdEutxtJ",
    "nome": "Abdominal Reto",
    "descricao": "",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Abdominal%20Reto%20execucao%20correta",
    "equipamento": "Peso Corporal",
    "dificuldade": "Iniciante",
    "ativo": true,
    "criadoPor": "system",
    "grupoMuscular": "Core/Abdômen",
    "videoUrl": "https://www.youtube.com/watch?v=Xyd_zL4vPy4"
  },
  {
    "exerciseId": "cyXa2964Gb6gIxKXHI88",
    "grupoMuscular": "Pernas - Quadríceps",
    "descricao": "",
    "nome": "Agachamento Livre",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Agachamento%20Livre%20execucao%20correta",
    "criadoPor": "system",
    "dificuldade": "Avançado",
    "videoUrl": "https://www.youtube.com/watch?v=ultWZbUMPL8",
    "equipamento": "Barra",
    "ativo": true
  },
  {
    "exerciseId": "d36lrHJ0Q8HivW3jUs10",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Desenvolvimento%20no%20Smith%20execucao%20correta",
    "grupoMuscular": "Ombros",
    "descricao": "",
    "dificuldade": "Intermediário",
    "ativo": true,
    "equipamento": "Máquina (Smith)",
    "videoUrl": "https://www.youtube.com/watch?v=cEwP8U0x47k",
    "nome": "Desenvolvimento no Smith",
    "criadoPor": "system"
  },
  {
    "exerciseId": "dLME0gDAShsEAInQPoMS",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Levantamento%20Terra%20Sum%C3%B4%20execucao%20correta",
    "grupoMuscular": "Costas",
    "descricao": "",
    "dificuldade": "Avançado",
    "ativo": true,
    "equipamento": "Barra",
    "videoUrl": "https://www.youtube.com/watch?v=iw40ly3Y8Q0",
    "nome": "Levantamento Terra Sumô",
    "criadoPor": "system"
  },
  {
    "exerciseId": "eLdEWsVjr4aFGapjDXhB",
    "ativo": true,
    "dificuldade": "Iniciante",
    "criadoPor": "system",
    "grupoMuscular": "Braços - Bíceps",
    "equipamento": "Halteres",
    "videoUrl": "https://www.youtube.com/watch?v=R_QeD5w8Vw8",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Rosca%20Simult%C3%A2nea%20com%20Halteres%20execucao%20correta",
    "descricao": "",
    "nome": "Rosca Simultânea com Halteres"
  },
  {
    "exerciseId": "ehFxgoyG4gE5pDFlue9D",
    "ativo": true,
    "grupoMuscular": "Peito",
    "descricao": "",
    "dificuldade": "Intermediário",
    "equipamento": "Barra",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Supino%20Reto%20com%20Barra%20execucao%20correta",
    "criadoPor": "system",
    "videoUrl": "https://www.youtube.com/watch?v=rT7DgCr-3pg",
    "nome": "Supino Reto com Barra"
  },
  {
    "exerciseId": "fm1HvItH3AYrmFb18Lrn",
    "ativo": true,
    "descricao": "",
    "grupoMuscular": "Core/Abdômen",
    "videoUrl": "https://www.youtube.com/watch?v=4mMfqWNO_n0",
    "equipamento": "Peso Corporal",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Abdominal%20Declinado%20execucao%20correta",
    "dificuldade": "Intermediário",
    "criadoPor": "system",
    "nome": "Abdominal Declinado"
  },
  {
    "exerciseId": "gcFUm9CLwwk9EJv8hNtv",
    "descricao": "",
    "nome": "Shrugs com Barra",
    "ativo": true,
    "criadoPor": "system",
    "grupoMuscular": "Costas",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Shrugs%20com%20Barra%20execucao%20correta",
    "videoUrl": "https://www.youtube.com/watch?v=cJRVVxmytaM",
    "dificuldade": "Iniciante",
    "equipamento": "Barra"
  },
  {
    "exerciseId": "hhQelA1Q6QrMdSRDtYqB",
    "criadoPor": "system",
    "nome": "Hip Thrust com Barra",
    "equipamento": "Barra",
    "dificuldade": "Intermediário",
    "grupoMuscular": "Pernas - Posteriores",
    "descricao": "",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Hip%20Thrust%20com%20Barra%20execucao%20correta",
    "videoUrl": "https://www.youtube.com/watch?v=xDmFkJxPzeM",
    "ativo": true
  },
  {
    "exerciseId": "iKpd7M1w0iETAZneGw3Q",
    "criadoPor": "system",
    "nome": "Supino Inclinado no Smith",
    "equipamento": "Máquina (Smith)",
    "dificuldade": "Intermediário",
    "grupoMuscular": "Peito",
    "descricao": "",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Supino%20Inclinado%20no%20Smith%20execucao%20correta",
    "videoUrl": "https://www.youtube.com/watch?v=TzT8X8_Kk8c",
    "ativo": true
  },
  {
    "exerciseId": "idaZvCqoKRNTAY2bdt0C",
    "grupoMuscular": "Costas",
    "nome": "Remada Articulada Fechada Unilateral",
    "criadoPor": "system",
    "videoUrl": "https://www.youtube.com/watch?v=rBv6vN6oNlI",
    "ativo": true,
    "equipamento": "Máquina",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Remada%20Articulada%20Fechada%20Unilateral%20execucao%20correta",
    "dificuldade": "Intermediário",
    "descricao": ""
  },
  {
    "exerciseId": "in43OVVf9qu06nYFl3ti",
    "nome": "Elevação de Pernas Suspenso",
    "dificuldade": "Avançado",
    "equipamento": "Peso Corporal",
    "criadoPor": "system",
    "videoUrl": "https://www.youtube.com/watch?v=Pr1ieGZ5atk",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Eleva%C3%A7%C3%A3o%20de%20Pernas%20Suspenso%20execucao%20correta",
    "ativo": true,
    "descricao": "",
    "grupoMuscular": "Core/Abdômen"
  },
  {
    "exerciseId": "jMb2yx6bA9L2ceAB65vg",
    "descricao": "",
    "nome": "Desenvolvimento com Barra",
    "grupoMuscular": "Ombros",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Desenvolvimento%20com%20Barra%20execucao%20correta",
    "equipamento": "Barra",
    "criadoPor": "system",
    "dificuldade": "Intermediário",
    "videoUrl": "https://www.youtube.com/watch?v=QAQ64hK4Xxs",
    "ativo": true
  },
  {
    "exerciseId": "jgboGqxNhNJbxYmunnUO",
    "grupoMuscular": "Core/Abdômen",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Prancha%20(Plank)%20execucao%20correta",
    "videoUrl": "https://www.youtube.com/watch?v=pSHjTRCQxIw",
    "descricao": "",
    "ativo": true,
    "equipamento": "Peso Corporal",
    "dificuldade": "Iniciante",
    "criadoPor": "system",
    "nome": "Prancha (Plank)"
  },
  {
    "exerciseId": "jmAzEeeLExlF1bCgrzUQ",
    "nome": "Glute Ham Raise",
    "videoUrl": "https://www.youtube.com/watch?v=VQqp5LAfBFs",
    "grupoMuscular": "Pernas - Posteriores",
    "criadoPor": "system",
    "ativo": true,
    "dificuldade": "Avançado",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Glute%20Ham%20Raise%20execucao%20correta",
    "equipamento": "Peso Corporal",
    "descricao": ""
  },
  {
    "exerciseId": "k5GQLLAPm4VzABVuS61W",
    "videoUrl": "https://www.youtube.com/watch?v=roCP6wCXPqo",
    "nome": "Remada Unilateral com Halter",
    "grupoMuscular": "Costas",
    "criadoPor": "system",
    "ativo": true,
    "dificuldade": "Iniciante",
    "equipamento": "Halteres",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Remada%20Unilateral%20com%20Halter%20execucao%20correta",
    "descricao": ""
  },
  {
    "exerciseId": "l8sinHUfqPfCIQrSuJQ9",
    "equipamento": "Barra",
    "ativo": true,
    "dificuldade": "Intermediário",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Supino%20Declinado%20com%20Barra%20execucao%20correta",
    "criadoPor": "system",
    "videoUrl": "https://www.youtube.com/watch?v=LfyQBUKR8SE",
    "descricao": "",
    "grupoMuscular": "Peito",
    "nome": "Supino Declinado com Barra"
  },
  {
    "exerciseId": "lI7NJZtrTVUKDQvqP8jw",
    "dificuldade": "Avançado",
    "grupoMuscular": "Core/Abdômen",
    "equipamento": "Máquina",
    "videoUrl": "https://www.youtube.com/watch?v=V0RcNkXqd4k",
    "criadoPor": "system",
    "nome": "Roda Abdominal",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Roda%20Abdominal%20execucao%20correta",
    "ativo": true,
    "descricao": ""
  },
  {
    "exerciseId": "lr5GkLf9aehMA2tFFOC9",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Eleva%C3%A7%C3%A3o%20Lateral%20execucao%20correta",
    "ativo": true,
    "videoUrl": "https://www.youtube.com/watch?v=3VcKaXpzqRo",
    "dificuldade": "Iniciante",
    "grupoMuscular": "Ombros",
    "criadoPor": "system",
    "equipamento": "Halteres",
    "nome": "Elevação Lateral",
    "descricao": ""
  },
  {
    "exerciseId": "lxaGVRmLGCL0ZsbZSYGN",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Barra%20Fixa%20Supinada%20(Chin-up)%20execucao%20correta",
    "ativo": true,
    "videoUrl": "https://www.youtube.com/watch?v=brhRXlOhkAA",
    "dificuldade": "Intermediário",
    "grupoMuscular": "Costas",
    "criadoPor": "system",
    "equipamento": "Peso Corporal",
    "nome": "Barra Fixa Supinada (Chin-up)",
    "descricao": ""
  },
  {
    "exerciseId": "m8MpSDTaYZg4mJEF45Cq",
    "grupoMuscular": "Costas",
    "criadoPor": "system",
    "dificuldade": "Intermediário",
    "equipamento": "Cabo",
    "ativo": true,
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Pullover%20no%20Cabo%20execucao%20correta",
    "nome": "Pullover no Cabo",
    "videoUrl": "https://www.youtube.com/watch?v=KwdlXmNhVZ0",
    "descricao": ""
  },
  {
    "exerciseId": "mnW9xBAc6mwDUaoHMqcS",
    "grupoMuscular": "Costas",
    "criadoPor": "system",
    "dificuldade": "Intermediário",
    "equipamento": "Cabo",
    "ativo": true,
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20High%20Row%20no%20Cabo%20no%20Banco%20execucao%20correta",
    "nome": "High Row no Cabo no Banco",
    "videoUrl": "https://www.youtube.com/watch?v=hS9gqj_7x_c",
    "descricao": ""
  },
  {
    "exerciseId": "mt0SN6xpQG1hVt0SytMh",
    "descricao": "",
    "nome": "Tríceps Corda",
    "grupoMuscular": "Braços - Tríceps",
    "videoUrl": "https://www.youtube.com/watch?v=2-LAMcpzODU",
    "equipamento": "Cabo",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Tr%C3%ADceps%20Corda%20execucao%20correta",
    "dificuldade": "Iniciante",
    "criadoPor": "system",
    "ativo": true
  },
  {
    "exerciseId": "n1febFCRrMS9lcKCEioC",
    "descricao": "",
    "nome": "Mergulho (Dips) nas Paralelas",
    "grupoMuscular": "Braços - Tríceps",
    "videoUrl": "https://www.youtube.com/watch?v=2z8JmcrW-As",
    "equipamento": "Peso Corporal",
    "dificuldade": "Intermediário",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Mergulho%20(Dips)%20nas%20Paralelas%20execucao%20correta",
    "criadoPor": "system",
    "ativo": true
  },
  {
    "exerciseId": "nODnPDjngs7G9JW7fRSH",
    "videoUrl": "https://www.youtube.com/watch?v=5H7VS8TdZVs",
    "dificuldade": "Iniciante",
    "equipamento": "Máquina/Barra",
    "descricao": "",
    "ativo": true,
    "nome": "Rosca Scott com Barra",
    "criadoPor": "system",
    "grupoMuscular": "Braços - Bíceps",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Rosca%20Scott%20com%20Barra%20execucao%20correta"
  },
  {
    "exerciseId": "p0ieQDoOPO95rcaDYMFn",
    "ativo": true,
    "criadoPor": "system",
    "dificuldade": "Iniciante",
    "grupoMuscular": "Costas",
    "videoUrl": "https://www.youtube.com/watch?v=qZ_kY8MQy7E",
    "equipamento": "Cabo",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Remada%20Alta%20com%20Corda%20execucao%20correta",
    "descricao": "",
    "nome": "Remada Alta com Corda"
  },
  {
    "exerciseId": "paLCVvTKTE7CEzCW8new",
    "descricao": "",
    "nome": "Panturrilha no Leg Press",
    "ativo": true,
    "criadoPor": "system",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Panturrilha%20no%20Leg%20Press%20execucao%20correta",
    "videoUrl": "https://www.youtube.com/watch?v=H-UvfN3Gs7c",
    "grupoMuscular": "Panturrilhas",
    "dificuldade": "Iniciante",
    "equipamento": "Máquina"
  },
  {
    "exerciseId": "px9Q26cZDm6t6LB8QEbV",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Face%20Pull%20execucao%20correta",
    "videoUrl": "https://www.youtube.com/watch?v=rep-qVOkqgk",
    "equipamento": "Cabo",
    "nome": "Face Pull",
    "dificuldade": "Intermediário",
    "criadoPor": "system",
    "grupoMuscular": "Ombros",
    "ativo": true,
    "descricao": ""
  },
  {
    "exerciseId": "qEIXm3ezbQjzUGDyhbOd",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Tr%C3%ADceps%20Barra%20execucao%20correta",
    "grupoMuscular": "Braços - Tríceps",
    "descricao": "",
    "dificuldade": "Iniciante",
    "ativo": true,
    "equipamento": "Cabo",
    "videoUrl": "https://www.youtube.com/watch?v=_gsUck-7M74",
    "nome": "Tríceps Barra",
    "criadoPor": "system"
  },
  {
    "exerciseId": "qH1vqMNt541rFXqYlcna",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Remada%20Sentado%20na%20M%C3%A1quina%20execucao%20correta",
    "grupoMuscular": "Costas",
    "descricao": "",
    "dificuldade": "Iniciante",
    "ativo": true,
    "equipamento": "Máquina",
    "videoUrl": "https://www.youtube.com/watch?v=7XxWAJySz0Y",
    "criadoPor": "system",
    "nome": "Remada Sentado na Máquina"
  },
  {
    "exerciseId": "qb8EmWyMWt6oEy2eE5BZ",
    "grupoMuscular": "Braços - Tríceps",
    "nome": "Tríceps Unilateral no Cabo",
    "descricao": "",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Tr%C3%ADceps%20Unilateral%20no%20Cabo%20execucao%20correta",
    "criadoPor": "system",
    "videoUrl": "https://www.youtube.com/watch?v=lKB9aVWyDxg",
    "dificuldade": "Iniciante",
    "equipamento": "Cabo",
    "ativo": true
  },
  {
    "exerciseId": "qpbOdtpbbRmYguzNYH52",
    "criadoPor": "system",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Pulldown%20com%20Corda%20execucao%20correta",
    "videoUrl": "https://www.youtube.com/watch?v=2w6vH2KnEkc",
    "ativo": true,
    "grupoMuscular": "Costas",
    "nome": "Pulldown com Corda",
    "dificuldade": "Intermediário",
    "descricao": "",
    "equipamento": "Cabo"
  },
  {
    "exerciseId": "sJiue1BdoW1R5gNsDXoy",
    "videoUrl": "https://www.youtube.com/watch?v=qNTdN97eYWE",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Rosca%20Scott%20com%20Halteres%20execucao%20correta",
    "dificuldade": "Iniciante",
    "equipamento": "Máquina/Halteres",
    "descricao": "",
    "nome": "Rosca Scott com Halteres",
    "grupoMuscular": "Braços - Bíceps",
    "ativo": true,
    "criadoPor": "system"
  },
  {
    "exerciseId": "sM3VxrVQGnYP7fOOClFK",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Mountain%20Climbers%20execucao%20correta",
    "descricao": "",
    "nome": "Mountain Climbers",
    "equipamento": "Peso Corporal",
    "dificuldade": "Iniciante",
    "ativo": true,
    "criadoPor": "system",
    "grupoMuscular": "Core/Abdômen",
    "videoUrl": "https://www.youtube.com/watch?v=nmwgirgXLYM"
  },
  {
    "exerciseId": "uU82RLmlY1ovPo3lzVn4",
    "descricao": "",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Prancha%20com%20Toque%20no%20Ombro%20execucao%20correta",
    "nome": "Prancha com Toque no Ombro",
    "equipamento": "Peso Corporal",
    "ativo": true,
    "dificuldade": "Intermediário",
    "criadoPor": "system",
    "grupoMuscular": "Core/Abdômen",
    "videoUrl": "https://www.youtube.com/watch?v=YqgQxYJKw3E"
  },
  {
    "exerciseId": "uaThcq9OWUuUx5U33cs8",
    "ativo": true,
    "videoUrl": "https://www.youtube.com/watch?v=EdtaJRBqwes",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Agachamento%20no%20Hack%20execucao%20correta",
    "descricao": "",
    "dificuldade": "Intermediário",
    "equipamento": "Máquina",
    "grupoMuscular": "Pernas - Quadríceps",
    "criadoPor": "system",
    "nome": "Agachamento no Hack"
  },
  {
    "exerciseId": "v9ZoQ7RcjAw3npgBB9tv",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Abdu%C3%A7%C3%A3o%20de%20Quadril%20na%20M%C3%A1quina%20execucao%20correta",
    "criadoPor": "system",
    "nome": "Abdução de Quadril na Máquina",
    "grupoMuscular": "Pernas - Posteriores",
    "dificuldade": "Iniciante",
    "equipamento": "Máquina",
    "ativo": true,
    "descricao": "",
    "videoUrl": "https://www.youtube.com/watch?v=3lboWqDZj2o"
  },
  {
    "exerciseId": "vmcYT7CGCRZ5zJWikf1z",
    "ativo": true,
    "grupoMuscular": "Pernas - Quadríceps",
    "descricao": "",
    "dificuldade": "Iniciante",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Agachamento%20Goblet%20execucao%20correta",
    "equipamento": "Halteres",
    "criadoPor": "system",
    "videoUrl": "https://www.youtube.com/watch?v=MeHQ4A4wO7A",
    "nome": "Agachamento Goblet"
  },
  {
    "exerciseId": "vrLEezs4WQFkL3cNzgtS",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Bicicleta%20Ergom%C3%A9trica%20execucao%20correta",
    "descricao": "",
    "ativo": true,
    "videoUrl": "https://www.youtube.com/watch?v=kYJ40R8H-z0",
    "grupoMuscular": "Cardio / Aeróbico",
    "equipamento": "Bicicleta Ergométrica",
    "dificuldade": "Iniciante",
    "criadoPor": "system",
    "nome": "Bicicleta Ergométrica"
  },
  {
    "exerciseId": "wW4YXkelaPTKqWKgUaMv",
    "criadoPor": "system",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Abdominal%20Bicicleta%20execucao%20correta",
    "nome": "Abdominal Bicicleta",
    "grupoMuscular": "Core/Abdômen",
    "descricao": "",
    "videoUrl": "https://www.youtube.com/watch?v=9FGilxCbdz8",
    "ativo": true,
    "dificuldade": "Intermediário",
    "equipamento": "Peso Corporal"
  },
  {
    "exerciseId": "xD70EhVByPEH2umlry7L",
    "criadoPor": "system",
    "grupoMuscular": "Core/Abdômen",
    "ativo": true,
    "nome": "Prancha Lateral",
    "dificuldade": "Intermediário",
    "equipamento": "Peso Corporal",
    "descricao": "",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Prancha%20Lateral%20execucao%20correta",
    "videoUrl": "https://www.youtube.com/watch?v=K2VljzCC7ig"
  },
  {
    "exerciseId": "xQlBdr6sc66dH0mgWKkz",
    "descricao": "",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Extens%C3%A3o%20de%20Tr%C3%ADceps%20na%20M%C3%A1quina%20execucao%20correta",
    "videoUrl": "https://www.youtube.com/watch?v=IDZZT0e2UHk",
    "grupoMuscular": "Braços - Tríceps",
    "ativo": true,
    "equipamento": "Máquina",
    "criadoPor": "system",
    "dificuldade": "Iniciante",
    "nome": "Extensão de Tríceps na Máquina"
  },
  {
    "exerciseId": "xUemVwryLSP5BhzPSHrg",
    "nome": "Levantamento Terra Romeno",
    "grupoMuscular": "Pernas - Posteriores",
    "criadoPor": "system",
    "descricao": "",
    "videoUrl": "https://www.youtube.com/watch?v=2SHsk9AzdjA",
    "equipamento": "Barra",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Levantamento%20Terra%20Romeno%20execucao%20correta",
    "ativo": true,
    "dificuldade": "Intermediário"
  },
  {
    "exerciseId": "ypjxN5lRd8O7euy72hMl",
    "videoUrl": "https://www.youtube.com/watch?v=yzvPiEqCi_U",
    "equipamento": "Máquina",
    "dificuldade": "Iniciante",
    "criadoPor": "system",
    "nome": "Mesa Flexora",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Mesa%20Flexora%20execucao%20correta",
    "grupoMuscular": "Pernas - Posteriores",
    "ativo": true,
    "descricao": ""
  },
  {
    "exerciseId": "ysMjxlOEADevCm3riil8",
    "nome": "Crucifixo Inclinado",
    "descricao": "",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Crucifixo%20Inclinado%20execucao%20correta",
    "dificuldade": "Iniciante",
    "equipamento": "Halteres",
    "ativo": true,
    "criadoPor": "system",
    "videoUrl": "https://www.youtube.com/watch?v=sAq_ocpRh_I",
    "grupoMuscular": "Peito"
  },
  {
    "exerciseId": "z2v2TQcJJ2mgCB5Ju07z",
    "videoUrl": "https://www.youtube.com/watch?v=y3y8fP0Ld-w",
    "descricao": "",
    "nome": "Flexão com Pausa",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Flex%C3%A3o%20com%20Pausa%20execucao%20correta",
    "ativo": true,
    "criadoPor": "system",
    "grupoMuscular": "Peito",
    "equipamento": "Peso Corporal",
    "dificuldade": "Avançado"
  },
  {
    "exerciseId": "z6u2kDVS1kDsX5BlN9CO",
    "dificuldade": "Avançado",
    "videoUrl": "https://www.youtube.com/watch?v=r0zr6kfhEJk",
    "equipamento": "Peso Corporal",
    "nome": "Sissy Squat",
    "descricao": "",
    "ativo": true,
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Sissy%20Squat%20execucao%20correta",
    "grupoMuscular": "Pernas - Quadríceps",
    "criadoPor": "system"
  },
  {
    "exerciseId": "zlMPZ1CtqKDTGFPWWSb6",
    "descricao": "",
    "videoUrl": "https://www.youtube.com/watch?v=YA-h3n29T3w",
    "grupoMuscular": "Costas",
    "dificuldade": "Intermediário",
    "equipamento": "Barra",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Good%20Morning%20execucao%20correta",
    "ativo": true,
    "nome": "Good Morning",
    "criadoPor": "system"
  },
  {
    "exerciseId": "zzYycHyRD8RE4Numo3TY",
    "criadoPor": "system",
    "grupoMuscular": "Braços - Bíceps",
    "nome": "Rosca Concentrada",
    "equipamento": "Halteres",
    "dificuldade": "Intermediário",
    "videoUrlPadrao": "https://www.youtube.com/results?search_query=como%20fazer%20Rosca%20Concentrada%20execucao%20correta",
    "descricao": "",
    "ativo": true,
    "videoUrl": "https://www.youtube.com/watch?v=0AUGkch3tzc"
  }
];
