export const quotesData = [
  "A única pessoa que você precisa vencer é a que você era ontem.",
  "Desafie-se hoje para ser mais forte amanhã.",
  "A dor de hoje será a força de amanhã.",
  "Não é sobre ser perfeito, é sobre ser melhor do que antes.",
  "O seu foco deve ser maior do que a preguiça!",
  "Disciplina é escolher entre o que você quer agora e o que você quer mais.",
  "Você não está treinando para ser aprovado pelos outros, mas para se superar.",
  "Um treino ruim é aquele que não aconteceu.",
  "Grandes resultados começam com pequenos passos consistentes.",
  "Não pare quando estiver cansado, pare quando terminar.",
  "O corpo alcança o que a mente acredita.",
  "Faça do seu próprio bem-estar a sua prioridade diária.",
  "Lembre-se do motivo pelo qual você começou quando a vontade de desistir bater.",
  "A consistência o levará a lugares que a motivação não consegue.",
  "Suor é apenas gordura chorando.",
  "Cada repetição é um passo em direção ao seu objetivo.",
  "O impossível é apenas uma grande palavra dita por pessoas pequenas.",
  "Aja hoje como a pessoa que você deseja se tornar amanhã.",
  "Não tenha medo de falhar, tenha medo de permanecer o mesmo.",
  "Você é mais forte do que a sua melhor desculpa.",
  "Treinar não é um castigo, é uma celebração de tudo que seu corpo é capaz de fazer.",
  "Sua saúde é o seu maior investimento.",
  "O cansaço passa, a conquista fica para sempre.",
  "Acorde com determinação, vá dormir com satisfação.",
  "Você está a um treino de um bom humor.",
  "O sucesso não é um lugar, é uma direção.",
  "Tudo o que você sempre quis está do outro lado do medo e da preguiça.",
  "Comece de onde você está. Use o que você tem. Faça o que você pode.",
  "Sua mente vai desistir mil vezes antes que seu corpo precise.",
  "Não conte os dias, faça os dias contarem.",
  "Obstáculos são aquelas coisas assustadoras que você vê quando tira os olhos do seu objetivo.",
  "Se te desafia, te transforma.",
  "Você é o projeto mais importante em que vai trabalhar na vida.",
  "Respeite o seu tempo, mas não use isso como desculpa para parar.",
  "A jornada importa muito mais que o destino final.",
  "Treine sua mente para ver o bom em cada situação, e foque na evolução.",
  "Hoje você se prepara para tudo o que sonhou realizar amanhã.",
  "Celebre cada pequena vitória diária, pois o somatório cria uma rotina forte.",
  "Não pergunte se vai doer, pergunte se vai valer a pena.",
  "Faça! Se der medo, faça com medo mesmo. Só não pare."
];
